name: Test CI

on: [push, pull_request]

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Clone the repo
        uses: actions/checkout@v4

      - name: Check flake configurations
        run: nix flake check --all-systems --show-trace

      - name: Attempt to build configurations
        run: nix build -L .#nixosConfigurations."robot".config.system.build.Script # .#deploy.nodes.robot.profiles.system.path
