name: "build"

on: [push, pull_request]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Clone the repo
        uses: actions/checkout@v4

      - name: Check flake configurations
        run: nix flake check --all-systems --show-trace

      - name: Attempt to build configurations
        run: nix build -L .#deploy.nodes.robot.profiles.system.path
